---

- name: basic packages
  apt:
    pkg:
      - acl
      - htop
      - nginx
      - certbot
      - python-certbot-nginx
    state: present
    force: "yes"
    update_cache: "yes"
  become: true

- name: Check that the raisin config exists
  stat:
    path: /etc/raisin.config.exs
  register: raisin_config

- name: copy raisin config
  copy:
    src: raisin.config.exs
    dest: /etc/raisin.config.exs
    mode: 0644
  when: not raisin_config.stat.exists
  become: yes

- name: make raisin directory
  file:
    dest: /home/deploy/raisin
    state: directory
  become: yes
  become_user: deploy

- name: Check that the nginx config exists
  stat:
    path: /etc/nginx/sites-enabled/raisin
  register: nginx_config

- name: copy nginx config
  copy:
    src: nginx.conf
    dest: /etc/nginx/sites-enabled/raisin
    mode: 0644
  when: not nginx_config.stat.exists
  become: yes

- name: copy nginx config
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  become: yes

- name: copy systemd file
  copy:
    src: raisin.service
    dest: /etc/systemd/system/raisin.service
  become: yes
  notify: reload systemd

- name: enable raisin service
  systemd:
    name: raisin.service
    enabled: yes
  become: yes

- name: link the v5 of ncurses.so
  file:
    src: /lib/x86_64-linux-gnu/libncursesw.so.5
    dest: /lib/x86_64-linux-gnu/libncursesw.so.6
    state: link
  become: yes

- name: setup backups folder
  file:
    path: /opt/backups/
    state: directory
  become: yes

- name: copy backup file
  copy:
    src: backup-raisin.sh
    dest: /opt/
    mode: 0744
  become: yes

- name: Backup the postgres database nightly
  cron:
    name: "pg dump"
    minute: "0"
    hour: "5"
    job: "/opt/backup-raisin.sh"
  become: yes
