---
- name: Create the deploy user
  user:
    name: deploy
    shell: /bin/bash
    password: "*"
  become: true

- name: Allow 'deploy' to have passwordless sudo star
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: ' start raisin'
    line: 'deploy ALL=(ALL) NOPASSWD: /bin/systemctl start raisin'
    validate: 'visudo -cf %s'
  become: true

- name: Allow 'deploy' to have passwordless sudo stop
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: ' stop raisin'
    line: 'deploy ALL=(ALL) NOPASSWD: /bin/systemctl stop raisin'
    validate: 'visudo -cf %s'
  become: true

- name: Allow 'deploy' to have passwordless sudo restart
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: ' restart raisin'
    line: 'deploy ALL=(ALL) NOPASSWD: /bin/systemctl restart raisin'
    validate: 'visudo -cf %s'
  become: true

- name: Forward SSH socket through sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    line: 'Defaults    env_keep+=SSH_AUTH_SOCK'
    validate: 'visudo -cf %s'
  become: true
